"""Real concurrency proof for message `sequence` ordering (docs/ROADMAP.md
Phase 5's own brief: "do not rely solely on timestamps... ensure
concurrent writers cannot create ambiguous ordering"). Real threads
against the real disposable Postgres, mirroring
tests/agency/test_onboarding_integration.py
::test_concurrent_acceptance_is_safe's exact shape. Marked `integration`,
excluded from the default `pytest` run.
"""

from __future__ import annotations

import threading
import uuid
from typing import cast

import pytest
from product.agency.provisioning import provision_agency, provision_client
from product.conversations.messages import MessageView, create_message, list_messages
from product.conversations.threads import create_thread
from product.crm.contacts import create_contact

from tests.conversations._cleanup import cleanup_tenant_tree, cleanup_users, make_user

pytestmark = pytest.mark.integration


def _name(prefix: str) -> str:
    return f"{prefix}-{uuid.uuid4().hex[:8]}"


def test_concurrent_message_writes_to_the_same_thread_get_distinct_sequences() -> None:
    """Two real threads race to insert a message into the SAME
    conversation thread at the same time, synchronized with a
    `threading.Barrier` so they genuinely contend. Postgres's own
    `GENERATED BY DEFAULT AS IDENTITY` column (product/migrations/versions
    /0014_...py) is what actually guarantees distinct values here -- this
    test proves that claim against a real database, not just the DDL."""
    owner = make_user()
    agency = provision_agency(owner.id, _name("agency"))
    client = provision_client(owner.id, agency.tenant_id, _name("client"))
    contact = create_contact(owner.id, client.tenant_id, first_name="Race", last_name="Condition")
    thread = create_thread(owner.id, client.tenant_id, contact_id=contact.id, channel="chat")
    try:
        barrier = threading.Barrier(2)
        results: dict[str, tuple[str, object]] = {}

        def _attempt(label: str, body: str) -> None:
            barrier.wait()
            try:
                message = create_message(
                    owner.id,
                    client.tenant_id,
                    thread.id,
                    direction="inbound",
                    is_internal_note=False,
                    body=body,
                    author_user_id=None,
                )
                results[label] = ("ok", message)
            except Exception as exc:  # noqa: BLE001 -- recorded for the assertion below, not swallowed
                results[label] = ("failed", exc)

        thread_a = threading.Thread(target=_attempt, args=("a", "from thread a"))
        thread_b = threading.Thread(target=_attempt, args=("b", "from thread b"))
        thread_a.start()
        thread_b.start()
        thread_a.join(timeout=30)
        thread_b.join(timeout=30)

        # Both must succeed -- unlike invitation acceptance (a genuine
        # single-winner race over one row), two concurrent message inserts
        # into the same thread are both legitimate, independent writes;
        # the only thing that must never happen is a collision or a lost
        # write.
        assert results["a"][0] == "ok", results["a"]
        assert results["b"][0] == "ok", results["b"]
        message_a = cast(MessageView, results["a"][1])
        message_b = cast(MessageView, results["b"][1])

        assert message_a.sequence != message_b.sequence

        listed = list_messages(owner.id, client.tenant_id, thread.id)
        assert len(listed) == 2
        sequences = [m.sequence for m in listed]
        assert len(set(sequences)) == 2, "two messages must never share a sequence value"
        # sequence-ordered read is deterministic, ascending, no gaps in
        # relative order between exactly these two rows.
        assert sequences == sorted(sequences)
    finally:
        cleanup_tenant_tree(client.tenant_id, agency.tenant_id)
        cleanup_users(owner.id)


def test_many_concurrent_writers_all_get_unique_sequences() -> None:
    """A higher-concurrency variant (10 writers) -- the identity column's
    guarantee should hold regardless of how many writers contend, not
    just at exactly two."""
    owner = make_user()
    agency = provision_agency(owner.id, _name("agency"))
    client = provision_client(owner.id, agency.tenant_id, _name("client"))
    contact = create_contact(owner.id, client.tenant_id, first_name="Ten", last_name="Writers")
    thread = create_thread(owner.id, client.tenant_id, contact_id=contact.id, channel="chat")
    writer_count = 10
    try:
        barrier = threading.Barrier(writer_count)
        results: list[MessageView | None] = [None] * writer_count
        errors: list[BaseException] = []

        def _attempt(index: int) -> None:
            barrier.wait()
            try:
                results[index] = create_message(
                    owner.id,
                    client.tenant_id,
                    thread.id,
                    direction="inbound",
                    is_internal_note=False,
                    body=f"writer-{index}",
                    author_user_id=None,
                )
            except BaseException as exc:  # noqa: BLE001 -- collected, not swallowed
                errors.append(exc)

        threads = [threading.Thread(target=_attempt, args=(i,)) for i in range(writer_count)]
        for t in threads:
            t.start()
        for t in threads:
            t.join(timeout=30)

        assert errors == [], errors
        sequences = [r.sequence for r in results if r is not None]
        assert len(sequences) == writer_count
        assert len(set(sequences)) == writer_count, "every writer must get a unique sequence"
    finally:
        cleanup_tenant_tree(client.tenant_id, agency.tenant_id)
        cleanup_users(owner.id)
