"""create conversations.messages table

Revision ID: 0014_conversations_messages
Revises: 0013_conversations_threads
Create Date: 2026-09-21 00:00:01.000000

docs/ROADMAP.md Phase 5.1. `thread_id` is a composite FK into
`conversations.threads`, `ON DELETE CASCADE` (a message has no
independent meaning without its thread).

`sequence` is a real Postgres `GENERATED BY DEFAULT AS IDENTITY` column
(`sa.Identity(always=False)` -- "BY DEFAULT", not "ALWAYS", so an
explicit value could still be supplied in an exceptional case, e.g. a
future data-migration/backfill tool, without needing an `OVERRIDING
SYSTEM VALUE` clause every ordinary INSERT would otherwise require;
ordinary application code, per `product/conversations/models.py`'s own
module docstring, never supplies one). This is the deterministic,
collision-proof ordering column `docs/ROADMAP.md` Phase 5's own brief
requires ("do not rely solely on timestamps... ensure concurrent writers
cannot create ambiguous ordering") -- proven against real concurrent
writers by `tests/conversations/test_concurrency_integration.py`, not
assumed from the DDL alone. `UNIQUE` on its own (not composite with
`tenant_id`) -- Postgres IDENTITY values are globally sequential across
every row in the table regardless of tenant, which is fine: ordering
*within* one thread by `sequence` is still fully deterministic and
collision-free even though the numbers themselves are not tenant-local.
"""

import os
import re
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

revision: str = "0014_conversations_messages"
down_revision: str | Sequence[str] | None = "0013_conversations_threads"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_DEFAULT_APP_ROLE = "product_app"


def _app_role() -> str:
    role = os.environ.get("APP_DB_USER", _DEFAULT_APP_ROLE)
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", role):
        raise ValueError(f"APP_DB_USER must be a plain SQL identifier, got: {role!r}")
    return role


def upgrade() -> None:
    app_role = _app_role()

    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("is_internal_note", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("author_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column(
            "sequence",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("tenant_id", "id", name="uq_conversations_messages_tenant_id_id"),
        sa.UniqueConstraint("sequence", name="uq_conversations_messages_sequence"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "thread_id"],
            ["conversations.threads.tenant_id", "conversations.threads.id"],
            name="fk_conversations_messages_tenant_thread",
            ondelete="CASCADE",
        ),
        schema="conversations",
    )
    op.create_index(
        "ix_conversations_messages_tenant_id", "messages", ["tenant_id"], schema="conversations"
    )
    op.create_index(
        "ix_conversations_messages_thread_id", "messages", ["thread_id"], schema="conversations"
    )
    op.create_index(
        "ix_conversations_messages_thread_id_sequence",
        "messages",
        ["thread_id", "sequence"],
        schema="conversations",
    )

    for statement in tenant_rls_statements("messages", schema="conversations"):
        op.execute(statement)

    op.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON conversations.messages TO "{app_role}"')


def downgrade() -> None:
    op.drop_table("messages", schema="conversations")
