"""create ai.tenant_policies table

Revision ID: 0041_ai_tenant_policies
Revises: 0040_durable_run_steps
Create Date: 2026-09-21 00:00:00.000000

docs/ROADMAP.md Phase 9.4. The persisted, tenant-scoped AI policy that
`product/ai/policy.py::resolve_tenant_ai_policy()` resolves into
`control_plane.data_authorization.TenantAIDataPolicy` -- storage for an
already-existing typed shape, never a second policy model.

Hand-written, not autogenerated. Creates the `ai` schema (this product's
first table in it) the same `CREATE SCHEMA IF NOT EXISTS` way every
earlier first-table-in-schema migration here does, and applies the
standard tenant Row-Level Security policy via
`infra.db.tenant_rls_statements()` -- the tenant isolation for this table
is enforced in PostgreSQL, not merely by application-level filtering.

`tenant_id` is the primary key: exactly one policy row per tenant, so a
duplicate policy for the same tenant is structurally impossible rather
than prevented by convention. No extra index is added -- the primary key
already covers every lookup this table has (always by `tenant_id`), and
an index that no query needs is just write cost.
"""

import os
import re
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

revision: str = "0041_ai_tenant_policies"
down_revision: str | Sequence[str] | None = "0040_durable_run_steps"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_DEFAULT_APP_ROLE = "product_app"


def _app_role() -> str:
    role = os.environ.get("APP_DB_USER", _DEFAULT_APP_ROLE)
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", role):
        raise ValueError(f"APP_DB_USER must be a plain SQL identifier, got: {role!r}")
    return role


def upgrade() -> None:
    app_role = _app_role()

    op.execute("CREATE SCHEMA IF NOT EXISTS ai")

    op.create_table(
        "tenant_policies",
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), primary_key=True),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "approved_capabilities",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'[]'::json"),
        ),
        sa.Column(
            "allowed_providers", sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")
        ),
        sa.Column("updated_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        schema="ai",
    )

    for statement in tenant_rls_statements("tenant_policies", schema="ai"):
        op.execute(statement)

    op.execute(f'GRANT USAGE ON SCHEMA ai TO "{app_role}"')
    op.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON ai.tenant_policies TO "{app_role}"')


def downgrade() -> None:
    # Mirrors 0001's own first-table-in-schema downgrade exactly: revoke,
    # drop the table, then drop the schema this migration created.
    app_role = _app_role()

    op.execute(f'REVOKE SELECT, INSERT, UPDATE, DELETE ON ai.tenant_policies FROM "{app_role}"')
    op.drop_table("tenant_policies", schema="ai")
    op.execute("DROP SCHEMA IF EXISTS ai")
