"""The Twilio inbound-webhook routes (docs/ROADMAP.md Phase 27.0).
Deliberately **not** added to `product/telephony/routes.py` -- that
router is read-only by its own explicit design
(`product/telephony/routes.py`'s own module docstring); these are the
first write/webhook routes this product adds, and they belong in their
own, vendor-owned module, mounted separately in `product/api/main.py`.

**Raw body preserved for signature verification.** Every route here reads
`await request.body()` -- the exact bytes Twilio sent -- and passes them
unchanged to `TwilioTelephonyProvider.verify_webhook_signature()` before
parsing a single field out of them.

**HIGH-2 remediation: signature verification is proxy-topology-agnostic.**
Only `request.url.path`/`request.url.query` (the ASGI-parsed request
line, never a `Host`/`X-Forwarded-*` header) are ever passed to
`verify_webhook_signature()`, as `path=`. The adapter itself combines
that path with its own already-trusted `TWILIO_VOICE_CALLBACK_BASE_URL`
configuration (never derived from this request) to build the one,
single, deterministic URL it verifies against -- see
`product/telephony/adapters/twilio_provider.py::TwilioTelephonyProvider
.verify_webhook_signature()`'s own docstring. This repository's actual
deployment topology (`deploy/caddy/Caddyfile.local`) proxies `/v1/*` to
the backend, but the backend's own container also publishes its port
directly (`docker-compose.yml`'s `backend` service), so a request can
reach this route either through the proxy or directly -- this design
verifies identically and correctly either way, and a forged `Host`/
`X-Forwarded-Host`/`X-Forwarded-Proto` header on a direct request has
zero effect on the URL used for verification, because none of those
headers are ever read for this purpose.

**Tenant resolution never trusts caller/webhook-supplied data as
authoritative on its own.**

- The **inbound-call** route resolves tenant exclusively through the
  existing, unchanged `product/telephony/calls.py
  ::receive_inbound_call_event()` -- via `to_number` -> `PhoneNumber` ->
  `tenant_id`, never from any field in the POST body.
- The **transfer-events** route reads `tenant_id`/`original_provider_call_id`/
  `attempt_id` from the URL *path* -- but that URL was generated by
  Marketstack's own server when it created the consultation leg
  (`TwilioTelephonyProvider.create_consultation_leg()`), never by the
  caller or by Twilio's own choice. An attacker cannot forge a different
  value in this URL and still produce a valid signature, because Twilio's
  signature is computed over this *exact* URL string using a secret
  (`TWILIO_AUTH_TOKEN`) the attacker does not hold -- the signature is the
  actual trust boundary; the path segments are a lookup convenience
  cryptographically bound to it, not a second, weaker authorization
  mechanism. `attempt_id` (HIGH-1 remediation) is what lets
  `product/telephony/transfer.py` reject a callback belonging to an
  already-superseded transfer attempt as stale.

**Twilio vocabulary stays inside this module.** `CallStatus` string
values, `CallSid`, and every other Twilio-specific field name are read and
translated here, then discarded -- only `product/telephony/calls.py`'s own
`EVENT_CALL_*`/`EVENT_TRANSFER_*` constants and plain strings cross into
the domain.
"""

from __future__ import annotations

import uuid
from urllib.parse import parse_qsl

from api.route_policy import public_route
from fastapi import APIRouter, Depends, Request, Response

from product.telephony.adapters.twilio_provider import TwilioTelephonyProvider
from product.telephony.calls import (
    EVENT_CALL_ANSWERED,
    EVENT_CALL_COMPLETED,
    EVENT_CALL_FAILED,
    EVENT_CALL_INITIATED,
    EVENT_CALL_NO_ANSWER,
    receive_inbound_call_event,
)
from product.telephony.errors import (
    TelephonyValidationError,
    TelephonyWebhookSignatureInvalidError,
)
from product.telephony.provider import ConsultationLeg
from product.telephony.transfer import (
    bridge_transfer,
    record_human_answered,
    record_transfer_failed,
)

router = APIRouter(prefix="/v1/telephony/adapters/twilio", tags=["telephony-twilio"])

#: Twilio's own documented `CallStatus` values for an inbound-call
#: webhook -- translated here into this product's own, already-existing
#: `EVENT_CALL_*` vocabulary. `queued`/`ringing` (the first delivery) map
#: to the one-time `call.initiated` event; every later delivery reports
#: the call's own terminal or in-progress state.
_INBOUND_STATUS_TO_EVENT: dict[str, str] = {
    "in-progress": EVENT_CALL_ANSWERED,
    "completed": EVENT_CALL_COMPLETED,
    "no-answer": EVENT_CALL_NO_ANSWER,
    "busy": EVENT_CALL_FAILED,
    "failed": EVENT_CALL_FAILED,
    "canceled": EVENT_CALL_FAILED,
}

_EMPTY_TWIML_RESPONSE = "<Response></Response>"


def _get_provider() -> TwilioTelephonyProvider:
    """A thin seam, not a caching singleton -- deliberately re-constructed
    per request so a test can monkeypatch this one function rather than
    reaching into module-level state. Mirrors the "no default provider,
    always explicit" discipline `product/telephony/provider.py`'s own
    module docstring establishes for every other telephony entrypoint."""
    return TwilioTelephonyProvider()


def _request_path(request: Request) -> str:
    """The request's own path+query ONLY (HIGH-2 remediation) -- never a
    scheme/host, and never anything derived from a `Host`/`X-Forwarded-*`
    header. See module docstring's own "signature verification is
    proxy-topology-agnostic" section."""
    if request.url.query:
        return f"{request.url.path}?{request.url.query}"
    return request.url.path


@router.post(
    "/inbound-call",
    dependencies=[Depends(public_route("Twilio webhook; authenticated by request signature"))],
)
async def inbound_call_webhook(request: Request) -> Response:
    body = await request.body()
    path = _request_path(request)
    fields = dict(parse_qsl(body.decode("utf-8"), keep_blank_values=True))

    call_sid = fields.get("CallSid")
    to_number = fields.get("To")
    from_number = fields.get("From")
    call_status = fields.get("CallStatus", "")
    if not call_sid or not to_number or not from_number:
        raise TelephonyValidationError("inbound Twilio webhook is missing required fields.")

    event_type = (
        EVENT_CALL_INITIATED
        if call_status in ("", "queued", "ringing")
        else _INBOUND_STATUS_TO_EVENT.get(call_status)
    )
    if event_type is None:
        # An unrecognized CallStatus -- recorded nowhere, no state change.
        # Never an error: an unrecognized value from the provider's own
        # perspective is not a security or client-input failure.
        return Response(content=_EMPTY_TWIML_RESPONSE, media_type="application/xml")

    provider = _get_provider()
    # `request.headers` (not `dict(request.headers)`) -- Starlette's own
    # `Headers` type is case-insensitive on `.get()`; flattening it into a
    # plain `dict` first would freeze in whatever case the ASGI server
    # delivered (lower-cased, per the ASGI spec), breaking an exact-case
    # header lookup a provider's own signature check might do.
    receive_inbound_call_event(
        provider=provider,
        headers=request.headers,
        body=body,
        provider_event_id=f"{call_sid}:{call_status or 'initiated'}",
        event_type=event_type,
        to_number=to_number,
        from_number=from_number,
        provider_call_id=call_sid,
        path=path,
    )
    return Response(content=_EMPTY_TWIML_RESPONSE, media_type="application/xml")


@router.post(
    "/transfer-events/{tenant_id}/{original_provider_call_id}/{attempt_id}",
    dependencies=[Depends(public_route("Twilio webhook; authenticated by request signature"))],
)
async def transfer_events_webhook(
    tenant_id: str, original_provider_call_id: str, attempt_id: str, request: Request
) -> Response:
    body = await request.body()
    path = _request_path(request)
    fields = dict(parse_qsl(body.decode("utf-8"), keep_blank_values=True))

    provider = _get_provider()
    if not provider.verify_webhook_signature(headers=request.headers, body=body, path=path):
        raise TelephonyWebhookSignatureInvalidError(
            "signature verification failed for a Twilio transfer-event callback."
        )

    consultation_sid = fields.get("CallSid")
    call_status = fields.get("CallStatus", "")
    if not consultation_sid:
        return Response(content=_EMPTY_TWIML_RESPONSE, media_type="application/xml")

    tenant_uuid = uuid.UUID(tenant_id)
    attempt_uuid = uuid.UUID(attempt_id)
    leg = ConsultationLeg(provider_leg_id=consultation_sid)

    if call_status == "in-progress":
        record_human_answered(
            tenant_id=tenant_uuid,
            provider_call_id=original_provider_call_id,
            provider=provider,
            consultation_leg=leg,
            attempt_id=attempt_uuid,
        )
        # `bridge_transfer()` already records its own `EVENT_TRANSFER_FAILED`
        # (`reason="bridge_failure"`) internally on a provider error, and
        # already performs its own atomic consume-before-bridge check
        # (HIGH-1 remediation) -- a stale/duplicate/superseded callback
        # here simply returns `False` with no provider call and no second
        # failure-handling branch needed.
        bridge_transfer(
            tenant_id=tenant_uuid,
            provider_call_id=original_provider_call_id,
            provider=provider,
            consultation_leg=leg,
            attempt_id=attempt_uuid,
        )
    elif call_status in ("busy", "no-answer", "failed", "canceled"):
        record_transfer_failed(
            tenant_id=tenant_uuid,
            provider_call_id=original_provider_call_id,
            provider=provider,
            request_id=consultation_sid,
            reason=call_status.replace("-", "_"),  # type: ignore[arg-type]
            attempt_id=attempt_uuid,
        )
    # "completed"/"queued"/"ringing" (and anything else): no-op -- see
    # module docstring's own "map only in-progress and the terminal
    # failure statuses" scope.

    return Response(content=_EMPTY_TWIML_RESPONSE, media_type="application/xml")


__all__ = ["router"]
