"""Message CRUD, the channel-agnostic core of the thread/message model
(docs/ROADMAP.md Phase 5.1, 5.5).

`create_message()` is the single function every message-producing path
funnels through -- an inbound message recorded from a webhook (future
phase), an internal note (`is_internal_note=True`), and a successfully
sent outbound message (`product/conversations/email_sending.py`/`sms.py`
/`whatsapp.py`, each calling this only *after* a real send succeeds, per
their own docstrings) all call this one function with explicit
`direction`/`is_internal_note`/`body`/`author_user_id` -- never inferred.
This is deliberate: there is exactly one code path that writes a
`conversations.messages` row, so the internal-note/outbound-message
distinction (5.5's own named checkpoint requirement) cannot drift between
two independently-maintained write paths.

**The internal-note isolation guarantee**: `create_message()` itself
never calls, imports, or references anything under `core.email`/`sms.py`
/`whatsapp.py` -- it only ever inserts a row. The *only* way a message
ever reaches a real provider is via `email_sending.py::send_email_message()`
(or the SMS/WhatsApp equivalents), which call `create_message()` **after**
a successful `core.email.send_email()`/provider `.send()` call, always
with `is_internal_note=False`. There is no code path from "a message row
exists with `is_internal_note=True`" to "a provider was invoked" --
proven by `tests/conversations/test_internal_note_isolation_integration.py`,
which asserts this structurally (two disjoint call graphs), not by
convention alone.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import datetime

from core.audit_log import ActorType, AuditOutcome, record
from infra.db import IntegrityError, select, tenant_session_scope

from product.conversations.errors import (
    ConversationReferenceNotFoundError,
    ConversationValidationError,
)
from product.conversations.models import (
    MAX_MESSAGE_BODY_LENGTH,
    VALID_DIRECTIONS,
    ConversationMessage,
)
from product.conversations.pagination import DEFAULT_PAGE_SIZE, clamp_limit
from product.conversations.permissions import THREAD_RESOURCE, require


@dataclass(frozen=True, slots=True)
class MessageView:
    id: uuid.UUID
    tenant_id: uuid.UUID
    thread_id: uuid.UUID
    direction: str
    is_internal_note: bool
    body: str
    author_user_id: uuid.UUID | None
    sequence: int
    created_at: datetime


def _to_view(row: ConversationMessage) -> MessageView:
    return MessageView(
        id=row.id,
        tenant_id=row.tenant_id,
        thread_id=row.thread_id,
        direction=row.direction,
        is_internal_note=row.is_internal_note,
        body=row.body,
        author_user_id=row.author_user_id,
        sequence=row.sequence,
        created_at=row.created_at,
    )


def create_message(
    actor_user_id: uuid.UUID,
    tenant_id: uuid.UUID,
    thread_id: uuid.UUID,
    *,
    direction: str,
    is_internal_note: bool,
    body: str,
    author_user_id: uuid.UUID | None,
) -> MessageView:
    require(actor_user_id, tenant_id, resource=THREAD_RESOURCE, action="update")
    if direction not in VALID_DIRECTIONS:
        raise ConversationValidationError(
            f"direction must be one of {VALID_DIRECTIONS}, got: {direction!r}"
        )
    if len(body) > MAX_MESSAGE_BODY_LENGTH:
        raise ConversationValidationError(
            f"body exceeds the {MAX_MESSAGE_BODY_LENGTH} character limit."
        )
    try:
        with tenant_session_scope(tenant_id) as session:
            row = ConversationMessage(
                tenant_id=tenant_id,
                thread_id=thread_id,
                direction=direction,
                is_internal_note=is_internal_note,
                body=body,
                author_user_id=author_user_id,
                # sequence: deliberately never set -- see
                # product/conversations/models.py's own docstring. Postgres's
                # GENERATED BY DEFAULT AS IDENTITY column supplies it.
            )
            session.add(row)
            session.flush()
            session.refresh(row)
            session.expunge(row)
    except IntegrityError as exc:
        # The composite FK on thread_id is the real validation (mirrors
        # product/conversations/threads.py::create_thread()'s own
        # identical reasoning for contact_id).
        raise ConversationReferenceNotFoundError("thread", thread_id) from exc
    record(
        tenant_id=tenant_id,
        actor_type=ActorType.USER,
        actor_user_id=actor_user_id,
        action="conversations.message.create",
        resource_type="conversations.message",
        resource_id=str(row.id),
        outcome=AuditOutcome.SUCCESS,
        # Identifiers and facts only -- never the message body (this
        # phase's own explicit personal-data requirement: audit metadata
        # must never carry conversation contents).
        metadata={
            "thread_id": str(thread_id),
            "direction": direction,
            "is_internal_note": is_internal_note,
        },
    )
    return _to_view(row)


def list_messages(
    actor_user_id: uuid.UUID,
    tenant_id: uuid.UUID,
    thread_id: uuid.UUID,
    *,
    limit: int = DEFAULT_PAGE_SIZE,
    offset: int = 0,
) -> list[MessageView]:
    require(actor_user_id, tenant_id, resource=THREAD_RESOURCE, action="read")
    bounded_limit = clamp_limit(limit)
    with tenant_session_scope(tenant_id) as session:
        rows = (
            session.execute(
                select(ConversationMessage)
                .where(
                    ConversationMessage.tenant_id == tenant_id,
                    ConversationMessage.thread_id == thread_id,
                )
                # sequence, never created_at -- see module docstring:
                # deterministic, collision-proof ordering.
                .order_by(ConversationMessage.sequence.asc())
                .limit(bounded_limit)
                .offset(max(offset, 0))
            )
            .scalars()
            .all()
        )
        for row in rows:
            session.expunge(row)
    return [_to_view(row) for row in rows]
