"""ORM models for the `conversations` schema (docs/ROADMAP.md Phase 5.1,
5.5).

Declared on the installed `saas-os` package's shared `infra.db` base and
primitives, exactly like `product/crm/models.py` -- this module never
imports `sqlalchemy` directly.

**Tenancy**: every table here is owned by the **client tenant** (the same
tenant CRM data lives in) -- a client's own customer conversations are
that client's own business data, for the identical reason `crm.*` data
is. An agency reaches a client's conversations via inherited `SUBTREE`
role, `get_current_actor` + service-layer `core.rbac.can()`, never
`get_tenant_context()` -- see `docs/ADR/0002-...`'s Phase 4 addendum,
which applies unchanged here. No new tenancy concept.

**Composite-FK discipline**, mirroring `product/crm/models.py` exactly:
`ConversationThread.contact_id` is a `ForeignKeyConstraint(["tenant_id",
"contact_id"], ["crm.contacts.tenant_id", "crm.contacts.id"])` --
structurally impossible for a thread to reference another tenant's
contact. `ConversationMessage.thread_id` is the identical pattern against
`conversations.threads`.

**Deletion behavior** (deliberate, documented, mirrors
`crm.opportunities.contact_id`'s own reasoning): `threads.contact_id` is
`ON DELETE SET NULL` -- deleting a contact must not destroy conversation
history, only unlink it. A thread is always linked to a real contact
**at creation time** (enforced by the service layer,
`product/conversations/threads.py::create_thread()` requires `contact_id`
and validates it belongs to `tenant_id`) even though the column itself
must be nullable to support `ON DELETE SET NULL` -- a thread whose
contact was later deleted becomes a legitimately unlinked thread, a real
historical state, not a bug (docs/ROADMAP.md Phase 5's own brief,
question 8). `messages.thread_id` is `ON DELETE CASCADE` -- a message has
no independent meaning without its thread, the same reasoning
`crm.tasks`/`crm.notes` already established for their own parent
entities.

**Message ordering**: `sequence` is a Postgres `GENERATED BY DEFAULT AS
IDENTITY` column (`product/migrations/versions/0014_...py`), never
derived from `created_at` -- two messages inserted in the same
transaction/millisecond would otherwise collide on `created_at` with no
deterministic tiebreaker; a Postgres identity column is atomically
assigned per-row by the database itself, so concurrent writers can never
receive the same value (proven by
`tests/conversations/test_concurrency_integration.py`, real threads
against real Postgres, not assumed). This model deliberately declares NO
Python-side default/value for `sequence` -- SQLAlchemy's unit-of-work
omits an attribute with no set value and no client-side default from the
INSERT column list entirely, which is what lets Postgres's own IDENTITY
default actually apply; `create_message()` never assigns `.sequence`
itself, and reads the real value back via `session.refresh()` after
flush, the same pattern already used for every other server-generated
column in this codebase (`created_at`, etc.).

`assigned_to_user_id`/`author_user_id` are plain (non-composite)
`ForeignKey("core.users.id")` -- `core.users` is a global/system table,
never tenant-scoped (`saas-os` ADR-0022's own table inventory: "a user is
never modeled as belonging to exactly one tenant"), the identical pattern
`tenant_id` itself already uses against `core.tenants.id`.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from infra.db import (
    Base,
    Boolean,
    DateTime,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Integer,
    Mapped,
    String,
    Text,
    UniqueConstraint,
    mapped_column,
    now,
)

CHANNEL_EMAIL = "email"
CHANNEL_SMS = "sms"
CHANNEL_WHATSAPP = "whatsapp"
CHANNEL_CHAT = "chat"
VALID_CHANNELS = (CHANNEL_EMAIL, CHANNEL_SMS, CHANNEL_WHATSAPP, CHANNEL_CHAT)

DIRECTION_INBOUND = "inbound"
DIRECTION_OUTBOUND = "outbound"
VALID_DIRECTIONS = (DIRECTION_INBOUND, DIRECTION_OUTBOUND)

# Enforced at the service/API layer (product/conversations/messages.py,
# routes.py's own Pydantic max_length) -- a real bound, not a DB CHECK,
# mirroring how crm.* bounds caller input at those same two layers.
MAX_MESSAGE_BODY_LENGTH = 10_000


class ConversationThread(Base):
    __tablename__ = "threads"
    __table_args__ = (
        UniqueConstraint("tenant_id", "id", name="uq_conversations_threads_tenant_id_id"),
        ForeignKeyConstraint(
            ["tenant_id", "contact_id"],
            ["crm.contacts.tenant_id", "crm.contacts.id"],
            name="fk_conversations_threads_tenant_contact",
            # "SET NULL (contact_id)", not bare "SET NULL" -- a real bug
            # found empirically (a test failure, not assumed): Postgres's
            # default ON DELETE SET NULL on a MULTI-COLUMN FK nulls out
            # every column in the FK, including tenant_id, which is
            # NOT NULL on this table -- the delete would fail with a
            # NotNullViolation instead of unlinking. Postgres 15+'s
            # column-scoped SET NULL syntax (this product runs Postgres
            # 16) nulls out only the named column(s). See
            # tests/conversations/test_threads_integration.py
            # ::test_deleting_contact_unlinks_thread_rather_than_deleting_it,
            # which failed before this fix and passes after it.
            ondelete="SET NULL (contact_id)",
        ),
        Index("ix_conversations_threads_tenant_id", "tenant_id"),
        Index("ix_conversations_threads_contact_id", "contact_id"),
        Index("ix_conversations_threads_assigned_to_user_id", "assigned_to_user_id"),
        {"schema": "conversations"},
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("core.tenants.id"), nullable=False)
    contact_id: Mapped[uuid.UUID | None] = mapped_column(nullable=True)
    channel: Mapped[str] = mapped_column(String(16), nullable=False)
    assigned_to_user_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("core.users.id"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=now(), onupdate=now()
    )


class ConversationMessage(Base):
    __tablename__ = "messages"
    __table_args__ = (
        UniqueConstraint("tenant_id", "id", name="uq_conversations_messages_tenant_id_id"),
        UniqueConstraint("sequence", name="uq_conversations_messages_sequence"),
        ForeignKeyConstraint(
            ["tenant_id", "thread_id"],
            ["conversations.threads.tenant_id", "conversations.threads.id"],
            name="fk_conversations_messages_tenant_thread",
            ondelete="CASCADE",
        ),
        Index("ix_conversations_messages_tenant_id", "tenant_id"),
        Index("ix_conversations_messages_thread_id", "thread_id"),
        Index("ix_conversations_messages_thread_id_sequence", "thread_id", "sequence"),
        {"schema": "conversations"},
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("core.tenants.id"), nullable=False)
    thread_id: Mapped[uuid.UUID] = mapped_column(nullable=False)
    direction: Mapped[str] = mapped_column(String(16), nullable=False)
    is_internal_note: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    author_user_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("core.users.id"), nullable=True
    )
    # server_default="0" is a marker, not real DDL -- see module
    # docstring's "Message ordering" section. A bug found empirically
    # (a NotNullViolation, not assumed): SQLAlchemy's ORM includes every
    # mapped column explicitly in the INSERT VALUES list, as NULL, unless
    # the column carries a server_default (any value) telling it "this is
    # server-populated, omit it and fetch the real value back via
    # RETURNING." This product's migrations are hand-written and never
    # derived from this model (`target_metadata = None`,
    # docs/REPOSITORY-STRATEGY.md), so this placeholder string is never
    # actually emitted as DDL anywhere -- the real DDL is
    # `product/migrations/versions/0014_...py`'s own
    # `sa.Identity(always=False)`. `session.refresh(row)` after flush (see
    # every service function below) loads the real, database-assigned
    # value regardless of what this placeholder says.
    sequence: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=now()
    )


class MessageTemplate(Base):
    __tablename__ = "message_templates"
    __table_args__ = (
        UniqueConstraint("tenant_id", "id", name="uq_conversations_message_templates_tenant_id_id"),
        UniqueConstraint(
            "tenant_id", "name", name="uq_conversations_message_templates_tenant_name"
        ),
        Index("ix_conversations_message_templates_tenant_id", "tenant_id"),
        {"schema": "conversations"},
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("core.tenants.id"), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    # NULL == usable for any channel; set == channel-specific.
    channel: Mapped[str | None] = mapped_column(String(16), nullable=True)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=now(), onupdate=now()
    )
